# sudo docker-compose up

version: '3'

services:
  ruby-script:
    container_name: run-ruby-script
    image: ruby
    working_dir: /usr/src/app
    command: [ "ruby", "main.rb" ]
    volumes:
      - ./:/usr/src/app
