version: '3'

services:
  nextcloud:
    container_name: nextcloud
    image: nextcloud
    restart: always
    ports:
      - 1234:80
    environment:
      NEXTCLOUD_TRUSTED_DOMAINS: 192.168.0.78
    volumes:
      - ./data:/var/www/html
