# sudo docker-compose up

version: '3'

services:
  python-script:
    container_name: run-python-script
    image: python
    working_dir: /usr/src/app
    command: [ "python", "main.py" ]
    volumes:
      - ./:/usr/src/app
