# sudo docker-compose up

version: '3'

services:
  node-script:
    container_name: run-ruby-script
    image: node
    working_dir: /usr/src/app
    command: [ "node", "main.js" ]
    volumes:
      - ./:/usr/src/app
