# sudo docker-compose up

version: '3'

services:
  php-script:
    container_name: run-php-script
    image: php
    working_dir: /usr/src/app
    command: [ "php", "main.php" ]
    volumes:
      - ./:/usr/src/app
